"""Convert DataSF Analysis Neighborhoods GeoJSON to a baked SVG-path asset
(site/hoods_geo.js): equirectangular projection, Douglas-Peucker
simplification, largest-ring label centroids, Farallon Islands dropped."""

import json
import math
from pathlib import Path

SCRATCH = Path(r"C:\Users\Luc\AppData\Local\Temp\claude"
               r"\C--Users-Luc-projects-sf-inspections"
               r"\294ed990-703c-4689-b989-426de118f4b1\scratchpad")
OUT = Path(r"C:\Users\Luc\projects\sf-inspections\site\hoods_geo.js")

gj = json.loads((SCRATCH / "hoods.geojson").read_text(encoding="utf-8"))

def rings_of(geom):
    if geom["type"] == "Polygon":
        return [geom["coordinates"][0]]
    return [poly[0] for poly in geom["coordinates"]]

# collect rings, drop Farallones (far west)
hoods = {}
for f in gj["features"]:
    name = f["properties"]["nhood"]
    keep = []
    for ring in rings_of(f["geometry"]):
        if sum(p[0] for p in ring) / len(ring) < -122.55:
            continue
        keep.append(ring)
    hoods[name] = keep

lons = [p[0] for rs in hoods.values() for r in rs for p in r]
lats = [p[1] for rs in hoods.values() for r in rs for p in r]
minlon, maxlon, minlat, maxlat = min(lons), max(lons), min(lats), max(lats)
klon = math.cos(math.radians((minlat + maxlat) / 2))
W = 720.0
scale = W / ((maxlon - minlon) * klon)
H = (maxlat - minlat) * scale

def proj(p):
    return ((p[0] - minlon) * klon * scale, (maxlat - p[1]) * scale)

def rdp(pts, eps):
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy)
    dmax, idx = -1.0, 0
    for i in range(1, len(pts) - 1):
        if norm < 1e-9:
            # degenerate chord (closed ring: first == last): use distance
            # to the endpoint, otherwise every d computes to exactly 0
            d = math.hypot(pts[i][0] - x1, pts[i][1] - y1)
        else:
            d = abs(dy * (pts[i][0] - x1) - dx * (pts[i][1] - y1)) / norm
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        left = rdp(pts[:idx + 1], eps)
        return left[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]

def ring_area(r):
    return abs(sum(r[i][0] * r[i + 1][1] - r[i + 1][0] * r[i][1]
                   for i in range(len(r) - 1))) / 2

out = {}
total_pts = 0
for name, rings in hoods.items():
    if not rings:
        print("WARNING: no rings for", name, "- skipped")
        continue
    parts, best, best_area = [], None, -1
    for ring in rings:
        pts = [proj(p) for p in ring]
        if ring_area(pts + [pts[0]]) < 6:  # sub-pixel islets: drop
            continue
        simp = rdp(pts, 1.6)
        if len(simp) < 4:
            continue
        total_pts += len(simp)
        d = "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in simp) + "Z"
        parts.append(d)
        a = ring_area(simp + [simp[0]])
        if a > best_area:
            best_area, best = a, simp
    if best is None:
        print("WARNING: nothing kept for", name, "- skipped")
        continue
    cx = sum(p[0] for p in best) / len(best)
    cy = sum(p[1] for p in best) / len(best)
    out[name] = {"d": "".join(parts), "cx": round(cx, 1), "cy": round(cy, 1)}

js = ("// SF Analysis Neighborhoods (DataSF j2bu-swwd), projected + simplified.\n"
      "// Generated by scripts: see scratchpad make_geo.py provenance in repo history.\n"
      f"const HOOD_GEO = {{ w: {W:.0f}, h: {H:.0f}, hoods: "
      + json.dumps(out, separators=(",", ":")) + " };\n")
OUT.write_text(js, encoding="utf-8")
print(f"neighborhoods: {len(out)}, points kept: {total_pts}, "
      f"file: {OUT.stat().st_size/1024:.0f} KB, viewbox {W:.0f}x{H:.0f}")
missing = set()
print("names match dataset:", sorted(out)[:3], "...")
